springdoc.api-docs.enabled=${SWAGGER_API_DOCS_ENABLED:true}
springdoc.swagger-ui.enabled=${SWAGGER_UI_ENABLED:true}
springdoc.swagger-ui.try-it-out-enabled=${SWAGGER_TRY_IT_OUT_ENABLED:true}

app.openapi.prod-url=${PROD_SERVER_URL:https://interview-portal.tatvasoft.com}
app.openapi.prod-description=Production Server
