springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.try-it-out-enabled=true

app.openapi.dev-url=${DEV_SERVER_URL:http://localhost:8080}
app.openapi.dev-description=Local Development Server
